set terminal png size 1600,1200 enhanced font "Arial,20"
set output 'chart.png'

color2 = "#96E8CB"; color3 = "#B2EDC5"; color4 = "#C1FFE2"; totalcolor = "#3C5A3E";
#set yrange [0:20]
set style data histogram
set style histogram cluster gap 1
set style fill solid
set xlabel "Year"
set ylabel "Number of studies" 
set boxwidth 0.9
set xtics format ""
set grid ytics
set key left top
set datafile separator ','

set title "Published multiomics Studies, per Year\n{/*0.7 (based on PubMed Keywords and Publication Date)}"
plot "results.dat" using 2:xtic(1) title "2-layered" linecolor rgb color2, \
     "results.dat" using 3 title "3-layered" linecolor rgb color3, \
     "results.dat" using 4 title ">3-layered" linecolor rgb color4, \
     "results.dat" using 5 title "total" linecolor rgb totalcolor 
